### ISSUE TITLE
Exclude pattern not working

### ISSUE THREAD

**Issue by szapp** [kirides/vdfsbuilder#1]
I played around with the vdfsbuilder, but I cannot get the `[EXCLUDE]` section in the VM script to be considered. I tried with both `vdfsbuilder.windows-amd64.exe` and `vdfsbuilder.linux-amd64` of v1.0.5.

Here is a minimal reproducible example VM script:
```
[BEGINVDF]
BaseDir=.\
VDFName=.\example.vdf

[FILES]
common-path\* -r

[EXCLUDE]
ignore -r

[INCLUDE]

[ENDVDF]
``` 
When using on the following directory tree, all files are included.
```
.
├── example.vm
└── common-path/
    ├── should-be-ignored/
    │   └── ignore
    └── should-be-included/
        └── include
```
This behavior is unchanged when changing `ignore -r` to `ignore` or when adding a wildcard for good measure (`i*nore` and `i*nore -r`). Also changing both file name and pattern to include an extension does not help.

Am I missing something here? Note that the pattern `ignore -r` works with GothicVDFS.

**Comment by kirides** [comment]
Excludes are currently not implemented.
See: https://github.com/kirides/vdfsbuilder/blob/main/vdf/writer.go#L403

Implementing them should be as simple as modifing https://github.com/kirides/vdfsbuilder/blob/main/vdf/writer.go#L85

to include a check against a blacklist (i.e. if `ok` is `true`, check against excludes)

**Comment by kirides** [comment]
@szapp i implemented `[EXCLUDE]` and `[INCLUDE]` in a way that i *think* should be ok.
See: https://github.com/kirides/vdfsbuilder/releases

Would you mind to check if it fits your needs?

See the updated README on how to use the paths in `[EXCLUDE]` and `[INCLUDE]`

It's mostly
- `file.ext` only matches relative to `BaseDir` which means it will only ever match `file.ext`
- `file.ext -r` matches relative to `BaseDir` and same name in any sub-directories `file.ext` and `dir\file.ext` will be matched
- `*.txt` will continue to match *all* `.txt` files no matter the directory they are in
- `_WORK\*` matches all files in `BASEDIR\_WORK\`
- `_WORK\* -r` matches all files in `BASEDIR\_WORK\` as well as in `BASEDIR\otherDir\_WORK\`

**Comment by szapp** [comment]
Nice, thanks a lot! I will gladly give it a try soon and see if these rules are sufficient consistent with GothicVDFS (if you haven't already). Just for compatibility purposes.

**Comment by szapp** [comment]
I tried to confirm the set of rules with GothicVDFS 2.6 (shipped with the ModKit of Gothic ***2***) to ensure some consistency with legacy VM files.

Most of the rules are consistent with GothicVDFS 2.6. However, for the third rule you listed here, I suggest to differentiate with the recursive flag. GothicVDFS does not match `*.txt` in sub-directories but only within `BaseDir`, whereas `*.txt -r` matches in all sub-directories. Aside from consistency with legacy files, that adjustment makes the recursive flag also more consistent compared to the other rules. Would you consider that?

In case you were not aware yet but are interested, the source code of GothicVDFS 2.6 is [available here](http://www.bendlins.de/nico/gothic2/). Some easy things I could spot from the source code that are either more or less obvious and probably reflected in vdfsbuilder already or irrelevant:

1. Pattern matching is case-insensitive
2. Path separator is `\` (the unix separator `/` is not considered)
3. For each file in the directory tree, the `INCLUDE` masks are checked first. Only if not matched the masks `FILES` and `EXCLUDE` are considered.
4. The masks `FILES`, `EXCLUDE`, and `INCLUDE` behave identically, i.e. `*` and `-r` are parsed the same way.

###### (Side note: I noticed that the GothicVDFS does have some minor bugs, like the matching of filenames that are longer than a mask, e.g. the root-folder 'directory' matches the mask 'dir' despite the lack of asterisk. But, of course, the vdfsbuilder should not re-implement this edge-case, buggy behavior.)

---

PS: I did NOT test the vdfsbuilder, just checked the behavior of GothicVDFS based on the rules you listed. However, I just noticed that the vdfsbuilder v1.0.8 does not fully consider `INCLUDE` masks. The following creates an empty VDF and does not include any files named `example.txt`:

```
[BEGINVDF]
BaseDir=.\
VDFName=.\example.vdf

[FILES]

[EXCLUDE]

[INCLUDE]
example.txt

[ENDVDF]
```

**Comment by kirides** [comment]
> PS: I did NOT test the vdfsbuilder, just checked the behavior of GothicVDFS based on the rules you listed. However, I just noticed that the vdfsbuilder v1.0.8 does not fully consider INCLUDE masks. The following creates an empty VDF and does not include any files named example.txt:

Correct, the way i implemented it up until now was:
1. Check `[FILES]` - Only include files that match
2. Check if any `[FILES]` should be `[EXCLUDE]`d
3. Check if any `[EXCLUDE]` should be `[INCLUDE]`d

slashes are always normalized to the current platform, `\` for windows and `/` for linux
This includes any filepaths aswell as the INCLUDE/EXCLUDE/FILES masks 

----

GothicVDFS itself does _either_ process `INCLUDE` or `FILES` then `EXCLUDE`, so you either always INCLUDE a specific pattern OR include a File Pattern if it's not excluded

```pas
function IsFileInMasks(Filename: PChar; const Masks: TSearchMasks): Boolean;
begin
  Result := False;
  if Masks.Include <> nil then
    Result := IsFileInMask(Filename, Masks.Include^);
  if (not Result) and (Masks.Files <> nil) then
    if IsFileInMask(Filename, Masks.Files^) then
      if Masks.Exclude <> nil then
        Result := not IsFileInMask(Filename, Masks.Exclude^)
      else
        Result := True;
end;
```

I will adjust the code to accomodate the behavior, aswell as the mentioned `*.txt` behavior, such that any wildcard only matches valid filenames without path separators.

The pattern matching will thus be changed to be more like this

```regex
# *.txt
# mind leading ^
^([^\\\s]+\.txt)$

# *.txt -r
# no leading ^
([^\\\s]+\.txt)$

# directory\*.txt
# mind leading ^
^(directory\/[^\\\s]+\.txt)$

# directory\*.txt -r
# no leading ^
(directory[^\\\s]+\.txt)$
```

**Comment by kirides** [comment]
@szapp Do you mind verifying that the changes do what you observe with GothicVDFS?

I've tried out some patterns with GothicVDFS and closely mimic the behavior of it.

**Comment by szapp** [comment]
@kirides Awesome, thanks for the quick adjustments!

I've done a few (non-systematic) tests and both GothicVDFS and vdfsbuilder v1.0.9 produce the same file structure. Thank you very much! I will let you know in case I encounter some unexpected outputs in the future.
