### ISSUE TITLE
Leading comment characters are stripped

### ISSUE THREAD

**Issue by szapp** [kirides/vdfsbuilder#5]
I noticed a strange behavior that when the `Comment` in the `[BEGINVDF]` block begins with a capital letter `C`, that character is stripped. For example: `Comment=Case in point` yields the comment "ase in point" in the resulting VDF.

I think I can pin point it to this line:

https://github.com/kirides/vdfsbuilder/blob/4ea144e3ee0021571a6cddacd20aeb89d752ea65/vdf/vm.go#L65

It seems the actual comment is stripped of the word `Comment=` (again). So `Comment=Comment of the VDF` will result in " of the VDF".

**Comment by kirides** [comment]
Yes the parsing uses the wrong method.

It should use strings/bytes.TrimPrefix instead of Trim left.

Former trims the specific text, while latter Trims any of the chars present in the cut-set (each char in `Comment=` will be trimmed from left on)
