### ISSUE TITLE
Support legacy VM line breaks in comments

### ISSUE THREAD

**Issue by szapp** [kirides/vdfsbuilder#6]
The GothicVDFS supports line breaks in the `Comment` of the `[BEGINVDF]` block by specifying `%%N`. This is then resolved to `0x0D` `0x0A` in the VDF.

It would be very nice if the vdfsbuilder would also support these!

---

This example script
```
[BEGINVDF]
Comment=Text%%Nwith%%Nnewlines
BaseDir=.\
VDFName=.\example.vdf
[FILES]
file.txt
[EXCLUDE]
[INCLUDE]
[ENDVDF]
```
results in
```
   5465 7874 0d0a 7769 7468 0d0a 6e65 776c 696e 6573 ....
//           ^^^^           ^^^^
// T e  x t       w i  t h       n e  w l  i n  e s
```
and looks like this

![image](https://github.com/kirides/vdfsbuilder/assets/20203034/521d1583-c619-400d-a2cc-3aea76a31b8a)

**Comment by kirides** [comment]
Should be easy enough to implement, as the comment is literally passed through.

A simple strings.ReplaceAll should do it
